project:
  type: website
  output-dir: docs

website:
  title: "Han-Yin's blog"
  description: "Database/Storage Systems"
  favicon: favicon.svg
  site-url: "https://smallfu666.github.io/blog"
  reader-mode: true
  image: favicon.svg
  open-graph: true
  navbar:
    pinned: false
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/Smallfu666

  page-footer:
    center:
      - text: "© Han-Yin Chang"

format:
  html:
    theme:
      light: claude-light.css
      dark: claude-dark.css
    toc: true
    include-after-body: toc-scrollspy.html

lang: en
date-format: "YYYY-MM-DD"
